// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.CloudCode.Response
{
    public partial class EconomyResponse
    {
        public string ID;
        public long Amount;

        [Preserve]
        public EconomyResponse ()
        {
        }
    }
}